version: '3'
services:
  python3:
    build: .
    container_name: 'Coontrol_Test'
    stdin_open: true
    working_dir: '/usr/src/app'
    tty: true
    volumes:
      - ${SRC_PATH}:/usr/src/app
    environment:
      - DISPLAY=192.168.0.191:0.0
